import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import imgBackground from "../public/images/layered-waves-haikei.svg";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<section className={styles.section}>
					<h1 className={styles.title}>Bonjour, je suis Hata !</h1>
					<h2 className={styles.subtitle}>Développeuse web</h2>
					<p className={styles.description}>
						Vous pourrez découvrir ici mon{" "}
						<Link href="/parcours" className={styles.links}>
							parcours
						</Link>{" "}
						et les{" "}
						<Link href="/projets" className={styles.links}>
							projets
						</Link>{" "}
						réalisés.
					</p>
				</section>
			</main>
		</div>
	);
}
